import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import './css/HomePage.css'
import { motion } from 'framer-motion';
import axiosClient from '../api/axiosClient';
import Loading from '../components/Loading';
import { useAuth } from '../contexts/AuthContext';



const HomePage: React.FC = () => {
    const [error, setError] = useState<string | null>(null);
    const [loading, setLoading] = useState<boolean>(true);
    const navigate = useNavigate();
    const { isAuthenticated } = useAuth();

    useEffect(() => {
        const fetchContent = async () => {
            setLoading(true);
            setError(null);
            const storedContent = localStorage.getItem('movies');
            // Check if content are already stored in localStorage
            if (storedContent) {

                setLoading(false);
                // return;
            }

            try {


            } catch (err) {
                const errorMessage = err instanceof Error ? err.message : String(err);
                setError(`Failed to load content. Please try again later: ${errorMessage}`);
            } finally {
                setLoading(false);
            }
        };

        fetchContent();
    }, []);



    return (
        <div className="home-page">
            <motion.div
                className="hero"
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                transition={{ duration: 1 }}
            >
                <motion.div
                    className="hero-content"
                    initial={{ opacity: 0, y: 40 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ duration: 1, delay: 0.5 }}
                >
                    <h1>Welcome to NaijaEdu</h1>
                    <p>
                        NaijaEdu is your AI-powered learning companion. Ask questions on any topic you want to learn, get instant, easy-to-understand content generated by AI, and test your knowledge with interactive quizzes. Learning has never been this engaging and personalized!
                    </p>
                    {!isAuthenticated && <>
                        <p>
                            Sign up now to start your personalized learning journey. It’s quick, easy, and free!
                        </p>
                        <button
                            className="cta-button"
                            onClick={() => navigate('/login')}
                        >
                            Get Started
                        </button>
                    </>}
                </motion.div>
            </motion.div>

            {loading && <Loading />}
            {error && <p className="error">{error}</p>}


            {
                error && (
                    <div className="error-container">
                        <p className="error-message">{error}</p>
                        <button className="retry-button" onClick={() => window.location.reload()}>
                            Retry
                        </button>
                    </div>
                )
            }

            {/* FEATURES */}
            <section className="features-section">
                <h2>Why NaijaEdu?</h2>
                <div className="features-grid">
                    {[
                        {
                            title: 'Instant Answers',
                            desc: 'Ask anything and get explanations tailored for Nigerian students.',
                            alt: 'Instant Answers',
                        },
                        {
                            title: 'Interactive Quizzes',
                            desc: 'Test your understanding with quizzes after every topic.',
                            alt: 'Quizzes',
                        },
                        {
                            title: 'Personalized Learning',
                            desc: 'Learn at your own pace with AI support.',
                            alt: 'Personalized Learning',
                        },
                    ].map((feature, index) => (
                        <motion.div
                            key={index}
                            className="feature-card"
                            initial={{ opacity: 0, y: 50 }}
                            whileInView={{ opacity: 1, y: 0 }}
                            transition={{ duration: 0.6, delay: index * 0.2 }}
                        >
                            <img src="https://via.placeholder.com/100" alt={feature.alt} />
                            <h3>{feature.title}</h3>
                            <p>{feature.desc}</p>
                        </motion.div>
                    ))}
                </div>
            </section>

            {/* HOW IT WORKS */}
            <section className="how-it-works">
                <h2>How It Works</h2>
                <li className="steps-list">
                    {[1, 2, 3, 4].map((step, i) => (
                        <motion.li
                            key={i}
                            initial={{ opacity: 0, x: -30 }}
                            whileInView={{ opacity: 1, x: 0 }}
                            transition={{ delay: i * 0.2, duration: 0.5 }}
                        >
                            {step}. Step description placeholder
                        </motion.li>
                    ))}
                </li>
            </section>

            {/* TESTIMONIALS */}
            <section className="testimonials">
                <h2>What Users Are Saying</h2>
                <motion.div
                    className="testimonial-card"
                    initial={{ opacity: 0, y: 30 }}
                    whileInView={{ opacity: 1, y: 0 }}
                    transition={{ duration: 0.6 }}
                    >
                    <p>“NaijaEdu makes learning fun and easy. I now understand topics I used to fear!”</p>
                    <strong>– Chika, SS2 Student</strong>
                </motion.div>

                <motion.div
                    className="testimonial-card"
                    initial={{ opacity: 0, y: 30 }}
                    whileInView={{ opacity: 1, y: 0 }}
                    transition={{ duration: 0.6, delay: 0.2 }}
                >
                    <p>“The quizzes are so useful, especially before tests. And I love the local examples!”</p>
                    <strong>– Musa, WAEC Candidate</strong>
                </motion.div>
            </section>
        </div >
    );
};

export default HomePage;